spring:
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDBMS_URI:localhost}:3306/findmypet?useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${RDBMS_USERNAME:root}
    password: ${RDBMS_PASSWORD:1234}

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  access-token:
    secret-key: ${ACCESS_SECRET_KEY}
    expire-millis: ${ACCESS_EXPIRE_MILLIS}
  refresh-token:
    secret-key: ${REFRESH_SECRET_KEY}
    expire-millis: ${REFRESH_EXPIRE_MILLIS}

auth:
  grant-type: authorization_code
  kakao:
    client-id:
  google:
    client-id:
    client-secret:

aws:
  s3:
    secret-key:
    access-ke:
    bucket-name:

cloud-front:
  domain: