name: Ci with Gradle build test

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      #      - name: Run ktlint
      #        uses: ScaCap/action-ktlint@master
      #        with:
      #          github_token: ${{ secrets.github_token }}
      #          reporter: github-pr-check

      - name: Run detekt
        uses: alaegin/Detekt-Action@v1.23.3
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt-config.yml
          detekt_build_upon_default_config: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #  To install packages associated with other private repositories that GITHUB_TOKEN can't access, use a personal access token (classic) with repository scope
      - name: Build and Test with Gradle
        run: ./gradlew clean build --parallel -x test --refresh-dependencies --stacktrace

      - name: Cleanup Gradle Cache
        if: ${{ always() }}
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties